name: seqRNN
channels:
  - defaults
dependencies:
  - python==2.7.18
  - numpy==1.14.5
  - tensorflow==1.10.0
  - scipy==1.1.0
  - scikit-learn==0.20.0
  - matplotlib==2.2.3
  - PyYAML==3.13
  - pip
  - pip:
    - git+https://github.com/mattgolub/recurrent-whisperer.git@v1.2.0#egg=recurrent-whisperer
